=begin comment

eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.1.17
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package EzmaxApi::ModuleCommunicationApi;

require 5.6.0;
use strict;
use warnings;
use utf8;
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use EzmaxApi::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'EzmaxApi::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = EzmaxApi::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# communication_get_communication_count_v1
#
# Get the number of communication
#
# @param string $e_communication_module Specify the requested module (required)
# @param int $pki_ezsignfolder_id The unique ID of the Ezsignfolder (optional)
{
    my $params = {
    'e_communication_module' => {
        data_type => 'string',
        description => 'Specify the requested module',
        required => '1',
    },
    'pki_ezsignfolder_id' => {
        data_type => 'int',
        description => 'The unique ID of the Ezsignfolder',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'communication_get_communication_count_v1' } = {
        summary => 'Get the number of communication',
        params => $params,
        returns => 'CommunicationGetCountV1Response',
        };
}
# @return CommunicationGetCountV1Response
#
sub communication_get_communication_count_v1 {
    my ($self, %args) = @_;

    # verify the required parameter 'e_communication_module' is set
    unless (exists $args{'e_communication_module'}) {
      croak("Missing the required parameter 'e_communication_module' when calling communication_get_communication_count_v1");
    }

    # parse inputs
    my $_resource_path = '/1/module/communication/getCommunicationCount';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'e_communication_module'}) {
        $query_params->{'eCommunicationModule'} = $self->{api_client}->to_query_value($args{'e_communication_module'});
    }

    # query params
    if ( exists $args{'pki_ezsignfolder_id'}) {
        $query_params->{'pkiEzsignfolderID'} = $self->{api_client}->to_query_value($args{'pki_ezsignfolder_id'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(Authorization )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('CommunicationGetCountV1Response', $response);
    return $_response_object;
}

#
# communication_get_communication_list_v1
#
# Retrieve communication list
#
# @param string $e_communication_module Specify the requested module (required)
# @param int $pki_ezsignfolder_id The unique ID of the Ezsignfolder (optional)
{
    my $params = {
    'e_communication_module' => {
        data_type => 'string',
        description => 'Specify the requested module',
        required => '1',
    },
    'pki_ezsignfolder_id' => {
        data_type => 'int',
        description => 'The unique ID of the Ezsignfolder',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'communication_get_communication_list_v1' } = {
        summary => 'Retrieve communication list',
        params => $params,
        returns => 'CommunicationGetListV1Response',
        };
}
# @return CommunicationGetListV1Response
#
sub communication_get_communication_list_v1 {
    my ($self, %args) = @_;

    # verify the required parameter 'e_communication_module' is set
    unless (exists $args{'e_communication_module'}) {
      croak("Missing the required parameter 'e_communication_module' when calling communication_get_communication_list_v1");
    }

    # parse inputs
    my $_resource_path = '/1/module/communication/getCommunicationList';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'e_communication_module'}) {
        $query_params->{'eCommunicationModule'} = $self->{api_client}->to_query_value($args{'e_communication_module'});
    }

    # query params
    if ( exists $args{'pki_ezsignfolder_id'}) {
        $query_params->{'pkiEzsignfolderID'} = $self->{api_client}->to_query_value($args{'pki_ezsignfolder_id'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(Authorization )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('CommunicationGetListV1Response', $response);
    return $_response_object;
}

1;
