=begin comment

eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.2.1
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package EzmaxApi::ObjectEzdoctemplatedocumentApi;

require 5.6.0;
use strict;
use warnings;
use utf8;
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use EzmaxApi::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'EzmaxApi::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = EzmaxApi::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# ezdoctemplatedocument_create_object_v1
#
# Create a new Ezdoctemplatedocument
#
# @param EzdoctemplatedocumentCreateObjectV1Request $ezdoctemplatedocument_create_object_v1_request  (required)
{
    my $params = {
    'ezdoctemplatedocument_create_object_v1_request' => {
        data_type => 'EzdoctemplatedocumentCreateObjectV1Request',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'ezdoctemplatedocument_create_object_v1' } = {
        summary => 'Create a new Ezdoctemplatedocument',
        params => $params,
        returns => 'EzdoctemplatedocumentCreateObjectV1Response',
        };
}
# @return EzdoctemplatedocumentCreateObjectV1Response
#
sub ezdoctemplatedocument_create_object_v1 {
    my ($self, %args) = @_;

    # verify the required parameter 'ezdoctemplatedocument_create_object_v1_request' is set
    unless (exists $args{'ezdoctemplatedocument_create_object_v1_request'}) {
      croak("Missing the required parameter 'ezdoctemplatedocument_create_object_v1_request' when calling ezdoctemplatedocument_create_object_v1");
    }

    # parse inputs
    my $_resource_path = '/1/object/ezdoctemplatedocument';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'ezdoctemplatedocument_create_object_v1_request'}) {
        $_body_data = $args{'ezdoctemplatedocument_create_object_v1_request'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(Authorization )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('EzdoctemplatedocumentCreateObjectV1Response', $response);
    return $_response_object;
}

#
# ezdoctemplatedocument_download_v1
#
# Retrieve the content
#
# @param int $pki_ezdoctemplatedocument_id  (required)
{
    my $params = {
    'pki_ezdoctemplatedocument_id' => {
        data_type => 'int',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'ezdoctemplatedocument_download_v1' } = {
        summary => 'Retrieve the content',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub ezdoctemplatedocument_download_v1 {
    my ($self, %args) = @_;

    # verify the required parameter 'pki_ezdoctemplatedocument_id' is set
    unless (exists $args{'pki_ezdoctemplatedocument_id'}) {
      croak("Missing the required parameter 'pki_ezdoctemplatedocument_id' when calling ezdoctemplatedocument_download_v1");
    }

    # parse inputs
    my $_resource_path = '/1/object/ezdoctemplatedocument/{pkiEzdoctemplatedocumentID}/download';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'pki_ezdoctemplatedocument_id'}) {
        my $_base_variable = "{" . "pkiEzdoctemplatedocumentID" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'pki_ezdoctemplatedocument_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(Authorization Presigned )];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

#
# ezdoctemplatedocument_edit_object_v1
#
# Edit an existing Ezdoctemplatedocument
#
# @param int $pki_ezdoctemplatedocument_id The unique ID of the Ezdoctemplatedocument (required)
# @param EzdoctemplatedocumentEditObjectV1Request $ezdoctemplatedocument_edit_object_v1_request  (required)
{
    my $params = {
    'pki_ezdoctemplatedocument_id' => {
        data_type => 'int',
        description => 'The unique ID of the Ezdoctemplatedocument',
        required => '1',
    },
    'ezdoctemplatedocument_edit_object_v1_request' => {
        data_type => 'EzdoctemplatedocumentEditObjectV1Request',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'ezdoctemplatedocument_edit_object_v1' } = {
        summary => 'Edit an existing Ezdoctemplatedocument',
        params => $params,
        returns => 'EzdoctemplatedocumentEditObjectV1Response',
        };
}
# @return EzdoctemplatedocumentEditObjectV1Response
#
sub ezdoctemplatedocument_edit_object_v1 {
    my ($self, %args) = @_;

    # verify the required parameter 'pki_ezdoctemplatedocument_id' is set
    unless (exists $args{'pki_ezdoctemplatedocument_id'}) {
      croak("Missing the required parameter 'pki_ezdoctemplatedocument_id' when calling ezdoctemplatedocument_edit_object_v1");
    }

    # verify the required parameter 'ezdoctemplatedocument_edit_object_v1_request' is set
    unless (exists $args{'ezdoctemplatedocument_edit_object_v1_request'}) {
      croak("Missing the required parameter 'ezdoctemplatedocument_edit_object_v1_request' when calling ezdoctemplatedocument_edit_object_v1");
    }

    # parse inputs
    my $_resource_path = '/1/object/ezdoctemplatedocument/{pkiEzdoctemplatedocumentID}';

    my $_method = 'PUT';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'pki_ezdoctemplatedocument_id'}) {
        my $_base_variable = "{" . "pkiEzdoctemplatedocumentID" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'pki_ezdoctemplatedocument_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # body params
    if ( exists $args{'ezdoctemplatedocument_edit_object_v1_request'}) {
        $_body_data = $args{'ezdoctemplatedocument_edit_object_v1_request'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(Authorization )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('EzdoctemplatedocumentEditObjectV1Response', $response);
    return $_response_object;
}

#
# ezdoctemplatedocument_get_autocomplete_v2
#
# Retrieve Ezdoctemplatedocuments and IDs
#
# @param string $s_selector The type of Ezdoctemplatedocuments to return (required)
# @param string $e_type The type of Ezdoctemplatedocument (required)
# @param string $fki_ezsignfoldertype_id Specify which fkiEzsignfoldertypeID we want to display. only used when eType &#x3D; Ezsignfoldertype (optional)
# @param string $e_filter_active Specify which results we want to display. (optional, default to 'Active')
# @param string $s_query Allow to filter the returned results (optional)
# @param HeaderAcceptLanguage $accept_language  (optional)
{
    my $params = {
    's_selector' => {
        data_type => 'string',
        description => 'The type of Ezdoctemplatedocuments to return',
        required => '1',
    },
    'e_type' => {
        data_type => 'string',
        description => 'The type of Ezdoctemplatedocument',
        required => '1',
    },
    'fki_ezsignfoldertype_id' => {
        data_type => 'string',
        description => 'Specify which fkiEzsignfoldertypeID we want to display. only used when eType &#x3D; Ezsignfoldertype',
        required => '0',
    },
    'e_filter_active' => {
        data_type => 'string',
        description => 'Specify which results we want to display.',
        required => '0',
    },
    's_query' => {
        data_type => 'string',
        description => 'Allow to filter the returned results',
        required => '0',
    },
    'accept_language' => {
        data_type => 'HeaderAcceptLanguage',
        description => '',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'ezdoctemplatedocument_get_autocomplete_v2' } = {
        summary => 'Retrieve Ezdoctemplatedocuments and IDs',
        params => $params,
        returns => 'EzdoctemplatedocumentGetAutocompleteV2Response',
        };
}
# @return EzdoctemplatedocumentGetAutocompleteV2Response
#
sub ezdoctemplatedocument_get_autocomplete_v2 {
    my ($self, %args) = @_;

    # verify the required parameter 's_selector' is set
    unless (exists $args{'s_selector'}) {
      croak("Missing the required parameter 's_selector' when calling ezdoctemplatedocument_get_autocomplete_v2");
    }

    # verify the required parameter 'e_type' is set
    unless (exists $args{'e_type'}) {
      croak("Missing the required parameter 'e_type' when calling ezdoctemplatedocument_get_autocomplete_v2");
    }

    # parse inputs
    my $_resource_path = '/2/object/ezdoctemplatedocument/getAutocomplete/{sSelector}';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'fki_ezsignfoldertype_id'}) {
        $query_params->{'fkiEzsignfoldertypeID'} = $self->{api_client}->to_query_value($args{'fki_ezsignfoldertype_id'});
    }

    # query params
    if ( exists $args{'e_type'}) {
        $query_params->{'eType'} = $self->{api_client}->to_query_value($args{'e_type'});
    }

    # query params
    if ( exists $args{'e_filter_active'}) {
        $query_params->{'eFilterActive'} = $self->{api_client}->to_query_value($args{'e_filter_active'});
    }

    # query params
    if ( exists $args{'s_query'}) {
        $query_params->{'sQuery'} = $self->{api_client}->to_query_value($args{'s_query'});
    }

    # header params
    if ( exists $args{'accept_language'}) {
        $header_params->{'Accept-Language'} = $self->{api_client}->to_header_value($args{'accept_language'});
    }

    # path params
    if ( exists $args{'s_selector'}) {
        my $_base_variable = "{" . "sSelector" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'s_selector'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(Authorization )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('EzdoctemplatedocumentGetAutocompleteV2Response', $response);
    return $_response_object;
}

#
# ezdoctemplatedocument_get_list_v1
#
# Retrieve Ezdoctemplatedocument list
#
# @param string $e_order_by Specify how you want the results to be sorted (optional)
# @param int $i_row_max  (optional)
# @param int $i_row_offset  (optional, default to 0)
# @param HeaderAcceptLanguage $accept_language  (optional)
# @param string $s_filter  (optional)
{
    my $params = {
    'e_order_by' => {
        data_type => 'string',
        description => 'Specify how you want the results to be sorted',
        required => '0',
    },
    'i_row_max' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    'i_row_offset' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    'accept_language' => {
        data_type => 'HeaderAcceptLanguage',
        description => '',
        required => '0',
    },
    's_filter' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'ezdoctemplatedocument_get_list_v1' } = {
        summary => 'Retrieve Ezdoctemplatedocument list',
        params => $params,
        returns => 'EzdoctemplatedocumentGetListV1Response',
        };
}
# @return EzdoctemplatedocumentGetListV1Response
#
sub ezdoctemplatedocument_get_list_v1 {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/1/object/ezdoctemplatedocument/getList';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'e_order_by'}) {
        $query_params->{'eOrderBy'} = $self->{api_client}->to_query_value($args{'e_order_by'});
    }

    # query params
    if ( exists $args{'i_row_max'}) {
        $query_params->{'iRowMax'} = $self->{api_client}->to_query_value($args{'i_row_max'});
    }

    # query params
    if ( exists $args{'i_row_offset'}) {
        $query_params->{'iRowOffset'} = $self->{api_client}->to_query_value($args{'i_row_offset'});
    }

    # query params
    if ( exists $args{'s_filter'}) {
        $query_params->{'sFilter'} = $self->{api_client}->to_query_value($args{'s_filter'});
    }

    # header params
    if ( exists $args{'accept_language'}) {
        $header_params->{'Accept-Language'} = $self->{api_client}->to_header_value($args{'accept_language'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(Authorization )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('EzdoctemplatedocumentGetListV1Response', $response);
    return $_response_object;
}

#
# ezdoctemplatedocument_get_object_v2
#
# Retrieve an existing Ezdoctemplatedocument
#
# @param int $pki_ezdoctemplatedocument_id The unique ID of the Ezdoctemplatedocument (required)
{
    my $params = {
    'pki_ezdoctemplatedocument_id' => {
        data_type => 'int',
        description => 'The unique ID of the Ezdoctemplatedocument',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'ezdoctemplatedocument_get_object_v2' } = {
        summary => 'Retrieve an existing Ezdoctemplatedocument',
        params => $params,
        returns => 'EzdoctemplatedocumentGetObjectV2Response',
        };
}
# @return EzdoctemplatedocumentGetObjectV2Response
#
sub ezdoctemplatedocument_get_object_v2 {
    my ($self, %args) = @_;

    # verify the required parameter 'pki_ezdoctemplatedocument_id' is set
    unless (exists $args{'pki_ezdoctemplatedocument_id'}) {
      croak("Missing the required parameter 'pki_ezdoctemplatedocument_id' when calling ezdoctemplatedocument_get_object_v2");
    }

    # parse inputs
    my $_resource_path = '/2/object/ezdoctemplatedocument/{pkiEzdoctemplatedocumentID}';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'pki_ezdoctemplatedocument_id'}) {
        my $_base_variable = "{" . "pkiEzdoctemplatedocumentID" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'pki_ezdoctemplatedocument_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(Authorization )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('EzdoctemplatedocumentGetObjectV2Response', $response);
    return $_response_object;
}

#
# ezdoctemplatedocument_patch_object_v1
#
# Patch an existing Ezdoctemplatedocument
#
# @param int $pki_ezdoctemplatedocument_id The unique ID of the Ezdoctemplatedocument (required)
# @param EzdoctemplatedocumentPatchObjectV1Request $ezdoctemplatedocument_patch_object_v1_request  (required)
{
    my $params = {
    'pki_ezdoctemplatedocument_id' => {
        data_type => 'int',
        description => 'The unique ID of the Ezdoctemplatedocument',
        required => '1',
    },
    'ezdoctemplatedocument_patch_object_v1_request' => {
        data_type => 'EzdoctemplatedocumentPatchObjectV1Request',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'ezdoctemplatedocument_patch_object_v1' } = {
        summary => 'Patch an existing Ezdoctemplatedocument',
        params => $params,
        returns => 'EzdoctemplatedocumentPatchObjectV1Response',
        };
}
# @return EzdoctemplatedocumentPatchObjectV1Response
#
sub ezdoctemplatedocument_patch_object_v1 {
    my ($self, %args) = @_;

    # verify the required parameter 'pki_ezdoctemplatedocument_id' is set
    unless (exists $args{'pki_ezdoctemplatedocument_id'}) {
      croak("Missing the required parameter 'pki_ezdoctemplatedocument_id' when calling ezdoctemplatedocument_patch_object_v1");
    }

    # verify the required parameter 'ezdoctemplatedocument_patch_object_v1_request' is set
    unless (exists $args{'ezdoctemplatedocument_patch_object_v1_request'}) {
      croak("Missing the required parameter 'ezdoctemplatedocument_patch_object_v1_request' when calling ezdoctemplatedocument_patch_object_v1");
    }

    # parse inputs
    my $_resource_path = '/1/object/ezdoctemplatedocument/{pkiEzdoctemplatedocumentID}';

    my $_method = 'PATCH';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'pki_ezdoctemplatedocument_id'}) {
        my $_base_variable = "{" . "pkiEzdoctemplatedocumentID" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'pki_ezdoctemplatedocument_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # body params
    if ( exists $args{'ezdoctemplatedocument_patch_object_v1_request'}) {
        $_body_data = $args{'ezdoctemplatedocument_patch_object_v1_request'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(Authorization )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('EzdoctemplatedocumentPatchObjectV1Response', $response);
    return $_response_object;
}

1;
