=begin comment

eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.3.1
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package EzmaxApi::ObjectTranqcontractApi;

require 5.6.0;
use strict;
use warnings;
use utf8;
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use EzmaxApi::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'EzmaxApi::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = EzmaxApi::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# tranqcontract_get_communication_count_v1
#
# Retrieve Communication count
#
# @param int $pki_tranqcontract_id  (required)
{
    my $params = {
    'pki_tranqcontract_id' => {
        data_type => 'int',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'tranqcontract_get_communication_count_v1' } = {
        summary => 'Retrieve Communication count',
        params => $params,
        returns => 'TranqcontractGetCommunicationCountV1Response',
        };
}
# @return TranqcontractGetCommunicationCountV1Response
#
sub tranqcontract_get_communication_count_v1 {
    my ($self, %args) = @_;

    # verify the required parameter 'pki_tranqcontract_id' is set
    unless (exists $args{'pki_tranqcontract_id'}) {
      croak("Missing the required parameter 'pki_tranqcontract_id' when calling tranqcontract_get_communication_count_v1");
    }

    # parse inputs
    my $_resource_path = '/1/object/tranqcontract/{pkiTranqcontractID}/getCommunicationCount';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'pki_tranqcontract_id'}) {
        my $_base_variable = "{" . "pkiTranqcontractID" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'pki_tranqcontract_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(Authorization )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('TranqcontractGetCommunicationCountV1Response', $response);
    return $_response_object;
}

#
# tranqcontract_get_communication_list_v1
#
# Retrieve Communication list
#
# @param int $pki_tranqcontract_id  (required)
{
    my $params = {
    'pki_tranqcontract_id' => {
        data_type => 'int',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'tranqcontract_get_communication_list_v1' } = {
        summary => 'Retrieve Communication list',
        params => $params,
        returns => 'TranqcontractGetCommunicationListV1Response',
        };
}
# @return TranqcontractGetCommunicationListV1Response
#
sub tranqcontract_get_communication_list_v1 {
    my ($self, %args) = @_;

    # verify the required parameter 'pki_tranqcontract_id' is set
    unless (exists $args{'pki_tranqcontract_id'}) {
      croak("Missing the required parameter 'pki_tranqcontract_id' when calling tranqcontract_get_communication_list_v1");
    }

    # parse inputs
    my $_resource_path = '/1/object/tranqcontract/{pkiTranqcontractID}/getCommunicationList';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'pki_tranqcontract_id'}) {
        my $_base_variable = "{" . "pkiTranqcontractID" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'pki_tranqcontract_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(Authorization )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('TranqcontractGetCommunicationListV1Response', $response);
    return $_response_object;
}

#
# tranqcontract_get_communicationrecipients_v1
#
# Retrieve Tranqcontract's Communicationrecipient
#
# @param int $pki_tranqcontract_id  (required)
{
    my $params = {
    'pki_tranqcontract_id' => {
        data_type => 'int',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'tranqcontract_get_communicationrecipients_v1' } = {
        summary => 'Retrieve Tranqcontract&#39;s Communicationrecipient',
        params => $params,
        returns => 'TranqcontractGetCommunicationrecipientsV1Response',
        };
}
# @return TranqcontractGetCommunicationrecipientsV1Response
#
sub tranqcontract_get_communicationrecipients_v1 {
    my ($self, %args) = @_;

    # verify the required parameter 'pki_tranqcontract_id' is set
    unless (exists $args{'pki_tranqcontract_id'}) {
      croak("Missing the required parameter 'pki_tranqcontract_id' when calling tranqcontract_get_communicationrecipients_v1");
    }

    # parse inputs
    my $_resource_path = '/1/object/tranqcontract/{pkiTranqcontractID}/getCommunicationrecipients';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'pki_tranqcontract_id'}) {
        my $_base_variable = "{" . "pkiTranqcontractID" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'pki_tranqcontract_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(Authorization )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('TranqcontractGetCommunicationrecipientsV1Response', $response);
    return $_response_object;
}

#
# tranqcontract_get_communicationsenders_v1
#
# Retrieve Tranqcontract's Communicationsender
#
# @param int $pki_tranqcontract_id  (required)
{
    my $params = {
    'pki_tranqcontract_id' => {
        data_type => 'int',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'tranqcontract_get_communicationsenders_v1' } = {
        summary => 'Retrieve Tranqcontract&#39;s Communicationsender',
        params => $params,
        returns => 'TranqcontractGetCommunicationsendersV1Response',
        };
}
# @return TranqcontractGetCommunicationsendersV1Response
#
sub tranqcontract_get_communicationsenders_v1 {
    my ($self, %args) = @_;

    # verify the required parameter 'pki_tranqcontract_id' is set
    unless (exists $args{'pki_tranqcontract_id'}) {
      croak("Missing the required parameter 'pki_tranqcontract_id' when calling tranqcontract_get_communicationsenders_v1");
    }

    # parse inputs
    my $_resource_path = '/1/object/tranqcontract/{pkiTranqcontractID}/getCommunicationsenders';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'pki_tranqcontract_id'}) {
        my $_base_variable = "{" . "pkiTranqcontractID" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'pki_tranqcontract_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(Authorization )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('TranqcontractGetCommunicationsendersV1Response', $response);
    return $_response_object;
}

#
# tranqcontract_import_into_edmv1
#
# Import attachments into the Tranqcontract
#
# @param int $pki_tranqcontract_id  (required)
# @param TranqcontractImportIntoEDMV1Request $tranqcontract_import_into_edmv1_request  (required)
{
    my $params = {
    'pki_tranqcontract_id' => {
        data_type => 'int',
        description => '',
        required => '1',
    },
    'tranqcontract_import_into_edmv1_request' => {
        data_type => 'TranqcontractImportIntoEDMV1Request',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'tranqcontract_import_into_edmv1' } = {
        summary => 'Import attachments into the Tranqcontract',
        params => $params,
        returns => 'TranqcontractImportIntoEDMV1Response',
        };
}
# @return TranqcontractImportIntoEDMV1Response
#
sub tranqcontract_import_into_edmv1 {
    my ($self, %args) = @_;

    # verify the required parameter 'pki_tranqcontract_id' is set
    unless (exists $args{'pki_tranqcontract_id'}) {
      croak("Missing the required parameter 'pki_tranqcontract_id' when calling tranqcontract_import_into_edmv1");
    }

    # verify the required parameter 'tranqcontract_import_into_edmv1_request' is set
    unless (exists $args{'tranqcontract_import_into_edmv1_request'}) {
      croak("Missing the required parameter 'tranqcontract_import_into_edmv1_request' when calling tranqcontract_import_into_edmv1");
    }

    # parse inputs
    my $_resource_path = '/1/object/tranqcontract/{pkiTranqcontractID}/importIntoEDM';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'pki_tranqcontract_id'}) {
        my $_base_variable = "{" . "pkiTranqcontractID" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'pki_tranqcontract_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # body params
    if ( exists $args{'tranqcontract_import_into_edmv1_request'}) {
        $_body_data = $args{'tranqcontract_import_into_edmv1_request'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(Authorization )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('TranqcontractImportIntoEDMV1Response', $response);
    return $_response_object;
}

1;
