=begin comment

eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.3.1
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package EzmaxApi::ObjectExternalbrokerApi;

require 5.6.0;
use strict;
use warnings;
use utf8;
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use EzmaxApi::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'EzmaxApi::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = EzmaxApi::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# externalbroker_import_into_edmv1
#
# Import attachments into the Externalbroker
#
# @param int $pki_externalbroker_id  (required)
# @param ExternalbrokerImportIntoEDMV1Request $externalbroker_import_into_edmv1_request  (required)
{
    my $params = {
    'pki_externalbroker_id' => {
        data_type => 'int',
        description => '',
        required => '1',
    },
    'externalbroker_import_into_edmv1_request' => {
        data_type => 'ExternalbrokerImportIntoEDMV1Request',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'externalbroker_import_into_edmv1' } = {
        summary => 'Import attachments into the Externalbroker',
        params => $params,
        returns => 'ExternalbrokerImportIntoEDMV1Response',
        };
}
# @return ExternalbrokerImportIntoEDMV1Response
#
sub externalbroker_import_into_edmv1 {
    my ($self, %args) = @_;

    # verify the required parameter 'pki_externalbroker_id' is set
    unless (exists $args{'pki_externalbroker_id'}) {
      croak("Missing the required parameter 'pki_externalbroker_id' when calling externalbroker_import_into_edmv1");
    }

    # verify the required parameter 'externalbroker_import_into_edmv1_request' is set
    unless (exists $args{'externalbroker_import_into_edmv1_request'}) {
      croak("Missing the required parameter 'externalbroker_import_into_edmv1_request' when calling externalbroker_import_into_edmv1");
    }

    # parse inputs
    my $_resource_path = '/1/object/externalbroker/{pkiExternalbrokerID}/importIntoEDM';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'pki_externalbroker_id'}) {
        my $_base_variable = "{" . "pkiExternalbrokerID" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'pki_externalbroker_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # body params
    if ( exists $args{'externalbroker_import_into_edmv1_request'}) {
        $_body_data = $args{'externalbroker_import_into_edmv1_request'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(Authorization )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ExternalbrokerImportIntoEDMV1Response', $response);
    return $_response_object;
}

1;
