=begin comment

eZmax API Definition

This API expose all the functionnalities for the eZmax and eZsign application.

The version of the OpenAPI document: 1.0.30
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('EzmaxApi::GlobalCustomerApi');

my $api = EzmaxApi::GlobalCustomerApi->new();
isa_ok($api, 'EzmaxApi::GlobalCustomerApi');

#
# global_customer_get_endpoint_v1 test
#
{
    my $pks_customer_code = undef; # replace NULL with a proper value
    my $s_infrastructureproduct_code = undef; # replace NULL with a proper value
    my $result = $api->global_customer_get_endpoint_v1(pks_customer_code => $pks_customer_code, s_infrastructureproduct_code => $s_infrastructureproduct_code);
}


1;
