=begin comment

eZmax API Definition

This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.0.46
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('EzmaxApi::ObjectEzsigndocumentApi');

my $api = EzmaxApi::ObjectEzsigndocumentApi->new();
isa_ok($api, 'EzmaxApi::ObjectEzsigndocumentApi');

#
# ezsigndocument_apply_ezsigntemplate_v1 test
#
# uncomment below and update the test
#my $ezsigndocument_apply_ezsigntemplate_v1_pki_ezsigndocument_id = undef; # replace NULL with a proper value
#my $ezsigndocument_apply_ezsigntemplate_v1_ezsigndocument_apply_ezsigntemplate_v1_request = undef; # replace NULL with a proper value
#my $ezsigndocument_apply_ezsigntemplate_v1_result = $api->ezsigndocument_apply_ezsigntemplate_v1(pki_ezsigndocument_id => $ezsigndocument_apply_ezsigntemplate_v1_pki_ezsigndocument_id, ezsigndocument_apply_ezsigntemplate_v1_request => $ezsigndocument_apply_ezsigntemplate_v1_ezsigndocument_apply_ezsigntemplate_v1_request);

#
# ezsigndocument_create_object_v1 test
#
# uncomment below and update the test
#my $ezsigndocument_create_object_v1_ezsigndocument_create_object_v1_request = undef; # replace NULL with a proper value
#my $ezsigndocument_create_object_v1_result = $api->ezsigndocument_create_object_v1(ezsigndocument_create_object_v1_request => $ezsigndocument_create_object_v1_ezsigndocument_create_object_v1_request);

#
# ezsigndocument_delete_object_v1 test
#
# uncomment below and update the test
#my $ezsigndocument_delete_object_v1_pki_ezsigndocument_id = undef; # replace NULL with a proper value
#my $ezsigndocument_delete_object_v1_result = $api->ezsigndocument_delete_object_v1(pki_ezsigndocument_id => $ezsigndocument_delete_object_v1_pki_ezsigndocument_id);

#
# ezsigndocument_get_children_v1 test
#
# uncomment below and update the test
#my $ezsigndocument_get_children_v1_pki_ezsigndocument_id = undef; # replace NULL with a proper value
#my $ezsigndocument_get_children_v1_result = $api->ezsigndocument_get_children_v1(pki_ezsigndocument_id => $ezsigndocument_get_children_v1_pki_ezsigndocument_id);

#
# ezsigndocument_get_download_url_v1 test
#
# uncomment below and update the test
#my $ezsigndocument_get_download_url_v1_pki_ezsigndocument_id = undef; # replace NULL with a proper value
#my $ezsigndocument_get_download_url_v1_e_document_type = undef; # replace NULL with a proper value
#my $ezsigndocument_get_download_url_v1_result = $api->ezsigndocument_get_download_url_v1(pki_ezsigndocument_id => $ezsigndocument_get_download_url_v1_pki_ezsigndocument_id, e_document_type => $ezsigndocument_get_download_url_v1_e_document_type);

#
# ezsigndocument_get_object_v1 test
#
# uncomment below and update the test
#my $ezsigndocument_get_object_v1_pki_ezsigndocument_id = undef; # replace NULL with a proper value
#my $ezsigndocument_get_object_v1_result = $api->ezsigndocument_get_object_v1(pki_ezsigndocument_id => $ezsigndocument_get_object_v1_pki_ezsigndocument_id);

