=begin comment

eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.2.1
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('EzmaxApi::ObjectCreditcardmerchantApi');

my $api = EzmaxApi::ObjectCreditcardmerchantApi->new();
isa_ok($api, 'EzmaxApi::ObjectCreditcardmerchantApi');

#
# creditcardmerchant_create_object_v1 test
#
# uncomment below and update the test
#my $creditcardmerchant_create_object_v1_creditcardmerchant_create_object_v1_request = undef; # replace NULL with a proper value
#my $creditcardmerchant_create_object_v1_result = $api->creditcardmerchant_create_object_v1(creditcardmerchant_create_object_v1_request => $creditcardmerchant_create_object_v1_creditcardmerchant_create_object_v1_request);

#
# creditcardmerchant_delete_object_v1 test
#
# uncomment below and update the test
#my $creditcardmerchant_delete_object_v1_pki_creditcardmerchant_id = undef; # replace NULL with a proper value
#my $creditcardmerchant_delete_object_v1_result = $api->creditcardmerchant_delete_object_v1(pki_creditcardmerchant_id => $creditcardmerchant_delete_object_v1_pki_creditcardmerchant_id);

#
# creditcardmerchant_edit_object_v1 test
#
# uncomment below and update the test
#my $creditcardmerchant_edit_object_v1_pki_creditcardmerchant_id = undef; # replace NULL with a proper value
#my $creditcardmerchant_edit_object_v1_creditcardmerchant_edit_object_v1_request = undef; # replace NULL with a proper value
#my $creditcardmerchant_edit_object_v1_result = $api->creditcardmerchant_edit_object_v1(pki_creditcardmerchant_id => $creditcardmerchant_edit_object_v1_pki_creditcardmerchant_id, creditcardmerchant_edit_object_v1_request => $creditcardmerchant_edit_object_v1_creditcardmerchant_edit_object_v1_request);

#
# creditcardmerchant_get_autocomplete_v2 test
#
# uncomment below and update the test
#my $creditcardmerchant_get_autocomplete_v2_s_selector = undef; # replace NULL with a proper value
#my $creditcardmerchant_get_autocomplete_v2_e_filter_active = undef; # replace NULL with a proper value
#my $creditcardmerchant_get_autocomplete_v2_s_query = undef; # replace NULL with a proper value
#my $creditcardmerchant_get_autocomplete_v2_accept_language = undef; # replace NULL with a proper value
#my $creditcardmerchant_get_autocomplete_v2_result = $api->creditcardmerchant_get_autocomplete_v2(s_selector => $creditcardmerchant_get_autocomplete_v2_s_selector, e_filter_active => $creditcardmerchant_get_autocomplete_v2_e_filter_active, s_query => $creditcardmerchant_get_autocomplete_v2_s_query, accept_language => $creditcardmerchant_get_autocomplete_v2_accept_language);

#
# creditcardmerchant_get_list_v1 test
#
# uncomment below and update the test
#my $creditcardmerchant_get_list_v1_e_order_by = undef; # replace NULL with a proper value
#my $creditcardmerchant_get_list_v1_i_row_max = undef; # replace NULL with a proper value
#my $creditcardmerchant_get_list_v1_i_row_offset = undef; # replace NULL with a proper value
#my $creditcardmerchant_get_list_v1_accept_language = undef; # replace NULL with a proper value
#my $creditcardmerchant_get_list_v1_s_filter = undef; # replace NULL with a proper value
#my $creditcardmerchant_get_list_v1_result = $api->creditcardmerchant_get_list_v1(e_order_by => $creditcardmerchant_get_list_v1_e_order_by, i_row_max => $creditcardmerchant_get_list_v1_i_row_max, i_row_offset => $creditcardmerchant_get_list_v1_i_row_offset, accept_language => $creditcardmerchant_get_list_v1_accept_language, s_filter => $creditcardmerchant_get_list_v1_s_filter);

#
# creditcardmerchant_get_object_v2 test
#
# uncomment below and update the test
#my $creditcardmerchant_get_object_v2_pki_creditcardmerchant_id = undef; # replace NULL with a proper value
#my $creditcardmerchant_get_object_v2_result = $api->creditcardmerchant_get_object_v2(pki_creditcardmerchant_id => $creditcardmerchant_get_object_v2_pki_creditcardmerchant_id);


done_testing();
