=begin comment

eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.2.0
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('EzmaxApi::ObjectEzsigndiscussionApi');

my $api = EzmaxApi::ObjectEzsigndiscussionApi->new();
isa_ok($api, 'EzmaxApi::ObjectEzsigndiscussionApi');

#
# ezsigndiscussion_create_object_v1 test
#
# uncomment below and update the test
#my $ezsigndiscussion_create_object_v1_ezsigndiscussion_create_object_v1_request = undef; # replace NULL with a proper value
#my $ezsigndiscussion_create_object_v1_result = $api->ezsigndiscussion_create_object_v1(ezsigndiscussion_create_object_v1_request => $ezsigndiscussion_create_object_v1_ezsigndiscussion_create_object_v1_request);

#
# ezsigndiscussion_delete_object_v1 test
#
# uncomment below and update the test
#my $ezsigndiscussion_delete_object_v1_pki_ezsigndiscussion_id = undef; # replace NULL with a proper value
#my $ezsigndiscussion_delete_object_v1_result = $api->ezsigndiscussion_delete_object_v1(pki_ezsigndiscussion_id => $ezsigndiscussion_delete_object_v1_pki_ezsigndiscussion_id);

#
# ezsigndiscussion_get_object_v2 test
#
# uncomment below and update the test
#my $ezsigndiscussion_get_object_v2_pki_ezsigndiscussion_id = undef; # replace NULL with a proper value
#my $ezsigndiscussion_get_object_v2_result = $api->ezsigndiscussion_get_object_v2(pki_ezsigndiscussion_id => $ezsigndiscussion_get_object_v2_pki_ezsigndiscussion_id);

