=begin comment

eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.1.14
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('EzmaxApi::ObjectEzsigntemplateformfieldgroupApi');

my $api = EzmaxApi::ObjectEzsigntemplateformfieldgroupApi->new();
isa_ok($api, 'EzmaxApi::ObjectEzsigntemplateformfieldgroupApi');

#
# ezsigntemplateformfieldgroup_create_object_v1 test
#
# uncomment below and update the test
#my $ezsigntemplateformfieldgroup_create_object_v1_ezsigntemplateformfieldgroup_create_object_v1_request = undef; # replace NULL with a proper value
#my $ezsigntemplateformfieldgroup_create_object_v1_result = $api->ezsigntemplateformfieldgroup_create_object_v1(ezsigntemplateformfieldgroup_create_object_v1_request => $ezsigntemplateformfieldgroup_create_object_v1_ezsigntemplateformfieldgroup_create_object_v1_request);

#
# ezsigntemplateformfieldgroup_delete_object_v1 test
#
# uncomment below and update the test
#my $ezsigntemplateformfieldgroup_delete_object_v1_pki_ezsigntemplateformfieldgroup_id = undef; # replace NULL with a proper value
#my $ezsigntemplateformfieldgroup_delete_object_v1_result = $api->ezsigntemplateformfieldgroup_delete_object_v1(pki_ezsigntemplateformfieldgroup_id => $ezsigntemplateformfieldgroup_delete_object_v1_pki_ezsigntemplateformfieldgroup_id);

#
# ezsigntemplateformfieldgroup_edit_object_v1 test
#
# uncomment below and update the test
#my $ezsigntemplateformfieldgroup_edit_object_v1_pki_ezsigntemplateformfieldgroup_id = undef; # replace NULL with a proper value
#my $ezsigntemplateformfieldgroup_edit_object_v1_ezsigntemplateformfieldgroup_edit_object_v1_request = undef; # replace NULL with a proper value
#my $ezsigntemplateformfieldgroup_edit_object_v1_result = $api->ezsigntemplateformfieldgroup_edit_object_v1(pki_ezsigntemplateformfieldgroup_id => $ezsigntemplateformfieldgroup_edit_object_v1_pki_ezsigntemplateformfieldgroup_id, ezsigntemplateformfieldgroup_edit_object_v1_request => $ezsigntemplateformfieldgroup_edit_object_v1_ezsigntemplateformfieldgroup_edit_object_v1_request);

#
# ezsigntemplateformfieldgroup_get_object_v1 test
#
# uncomment below and update the test
#my $ezsigntemplateformfieldgroup_get_object_v1_pki_ezsigntemplateformfieldgroup_id = undef; # replace NULL with a proper value
#my $ezsigntemplateformfieldgroup_get_object_v1_result = $api->ezsigntemplateformfieldgroup_get_object_v1(pki_ezsigntemplateformfieldgroup_id => $ezsigntemplateformfieldgroup_get_object_v1_pki_ezsigntemplateformfieldgroup_id);

#
# ezsigntemplateformfieldgroup_get_object_v2 test
#
# uncomment below and update the test
#my $ezsigntemplateformfieldgroup_get_object_v2_pki_ezsigntemplateformfieldgroup_id = undef; # replace NULL with a proper value
#my $ezsigntemplateformfieldgroup_get_object_v2_result = $api->ezsigntemplateformfieldgroup_get_object_v2(pki_ezsigntemplateformfieldgroup_id => $ezsigntemplateformfieldgroup_get_object_v2_pki_ezsigntemplateformfieldgroup_id);

