=begin comment

eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.2.0
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('EzmaxApi::ObjectEzmaxinvoicingApi');

my $api = EzmaxApi::ObjectEzmaxinvoicingApi->new();
isa_ok($api, 'EzmaxApi::ObjectEzmaxinvoicingApi');

#
# ezmaxinvoicing_get_autocomplete_v2 test
#
# uncomment below and update the test
#my $ezmaxinvoicing_get_autocomplete_v2_s_selector = undef; # replace NULL with a proper value
#my $ezmaxinvoicing_get_autocomplete_v2_e_filter_active = undef; # replace NULL with a proper value
#my $ezmaxinvoicing_get_autocomplete_v2_s_query = undef; # replace NULL with a proper value
#my $ezmaxinvoicing_get_autocomplete_v2_accept_language = undef; # replace NULL with a proper value
#my $ezmaxinvoicing_get_autocomplete_v2_result = $api->ezmaxinvoicing_get_autocomplete_v2(s_selector => $ezmaxinvoicing_get_autocomplete_v2_s_selector, e_filter_active => $ezmaxinvoicing_get_autocomplete_v2_e_filter_active, s_query => $ezmaxinvoicing_get_autocomplete_v2_s_query, accept_language => $ezmaxinvoicing_get_autocomplete_v2_accept_language);

#
# ezmaxinvoicing_get_object_v2 test
#
# uncomment below and update the test
#my $ezmaxinvoicing_get_object_v2_pki_ezmaxinvoicing_id = undef; # replace NULL with a proper value
#my $ezmaxinvoicing_get_object_v2_result = $api->ezmaxinvoicing_get_object_v2(pki_ezmaxinvoicing_id => $ezmaxinvoicing_get_object_v2_pki_ezmaxinvoicing_id);

#
# ezmaxinvoicing_get_provisional_v1 test
#
# uncomment below and update the test
#my $ezmaxinvoicing_get_provisional_v1_result = $api->ezmaxinvoicing_get_provisional_v1();


done_testing();
