=begin comment

eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.2.1
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('EzmaxApi::ObjectEzsigntemplatedocumentpagerecognitionApi');

my $api = EzmaxApi::ObjectEzsigntemplatedocumentpagerecognitionApi->new();
isa_ok($api, 'EzmaxApi::ObjectEzsigntemplatedocumentpagerecognitionApi');

#
# ezsigntemplatedocumentpagerecognition_create_object_v1 test
#
# uncomment below and update the test
#my $ezsigntemplatedocumentpagerecognition_create_object_v1_ezsigntemplatedocumentpagerecognition_create_object_v1_request = undef; # replace NULL with a proper value
#my $ezsigntemplatedocumentpagerecognition_create_object_v1_result = $api->ezsigntemplatedocumentpagerecognition_create_object_v1(ezsigntemplatedocumentpagerecognition_create_object_v1_request => $ezsigntemplatedocumentpagerecognition_create_object_v1_ezsigntemplatedocumentpagerecognition_create_object_v1_request);

#
# ezsigntemplatedocumentpagerecognition_delete_object_v1 test
#
# uncomment below and update the test
#my $ezsigntemplatedocumentpagerecognition_delete_object_v1_pki_ezsigntemplatedocumentpagerecognition_id = undef; # replace NULL with a proper value
#my $ezsigntemplatedocumentpagerecognition_delete_object_v1_result = $api->ezsigntemplatedocumentpagerecognition_delete_object_v1(pki_ezsigntemplatedocumentpagerecognition_id => $ezsigntemplatedocumentpagerecognition_delete_object_v1_pki_ezsigntemplatedocumentpagerecognition_id);

#
# ezsigntemplatedocumentpagerecognition_edit_object_v1 test
#
# uncomment below and update the test
#my $ezsigntemplatedocumentpagerecognition_edit_object_v1_pki_ezsigntemplatedocumentpagerecognition_id = undef; # replace NULL with a proper value
#my $ezsigntemplatedocumentpagerecognition_edit_object_v1_ezsigntemplatedocumentpagerecognition_edit_object_v1_request = undef; # replace NULL with a proper value
#my $ezsigntemplatedocumentpagerecognition_edit_object_v1_result = $api->ezsigntemplatedocumentpagerecognition_edit_object_v1(pki_ezsigntemplatedocumentpagerecognition_id => $ezsigntemplatedocumentpagerecognition_edit_object_v1_pki_ezsigntemplatedocumentpagerecognition_id, ezsigntemplatedocumentpagerecognition_edit_object_v1_request => $ezsigntemplatedocumentpagerecognition_edit_object_v1_ezsigntemplatedocumentpagerecognition_edit_object_v1_request);

#
# ezsigntemplatedocumentpagerecognition_get_object_v2 test
#
# uncomment below and update the test
#my $ezsigntemplatedocumentpagerecognition_get_object_v2_pki_ezsigntemplatedocumentpagerecognition_id = undef; # replace NULL with a proper value
#my $ezsigntemplatedocumentpagerecognition_get_object_v2_result = $api->ezsigntemplatedocumentpagerecognition_get_object_v2(pki_ezsigntemplatedocumentpagerecognition_id => $ezsigntemplatedocumentpagerecognition_get_object_v2_pki_ezsigntemplatedocumentpagerecognition_id);


done_testing();
