=begin comment

eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.2.1
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('EzmaxApi::ObjectElectronicfundstransferApi');

my $api = EzmaxApi::ObjectElectronicfundstransferApi->new();
isa_ok($api, 'EzmaxApi::ObjectElectronicfundstransferApi');

#
# electronicfundstransfer_get_communication_list_v1 test
#
# uncomment below and update the test
#my $electronicfundstransfer_get_communication_list_v1_pki_electronicfundstransfer_id = undef; # replace NULL with a proper value
#my $electronicfundstransfer_get_communication_list_v1_result = $api->electronicfundstransfer_get_communication_list_v1(pki_electronicfundstransfer_id => $electronicfundstransfer_get_communication_list_v1_pki_electronicfundstransfer_id);


done_testing();
