=begin comment

eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.2.1
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('EzmaxApi::ObjectEzdoctemplatedocumentApi');

my $api = EzmaxApi::ObjectEzdoctemplatedocumentApi->new();
isa_ok($api, 'EzmaxApi::ObjectEzdoctemplatedocumentApi');

#
# ezdoctemplatedocument_create_object_v1 test
#
# uncomment below and update the test
#my $ezdoctemplatedocument_create_object_v1_ezdoctemplatedocument_create_object_v1_request = undef; # replace NULL with a proper value
#my $ezdoctemplatedocument_create_object_v1_result = $api->ezdoctemplatedocument_create_object_v1(ezdoctemplatedocument_create_object_v1_request => $ezdoctemplatedocument_create_object_v1_ezdoctemplatedocument_create_object_v1_request);

#
# ezdoctemplatedocument_download_v1 test
#
# uncomment below and update the test
#my $ezdoctemplatedocument_download_v1_pki_ezdoctemplatedocument_id = undef; # replace NULL with a proper value
#my $ezdoctemplatedocument_download_v1_result = $api->ezdoctemplatedocument_download_v1(pki_ezdoctemplatedocument_id => $ezdoctemplatedocument_download_v1_pki_ezdoctemplatedocument_id);

#
# ezdoctemplatedocument_edit_object_v1 test
#
# uncomment below and update the test
#my $ezdoctemplatedocument_edit_object_v1_pki_ezdoctemplatedocument_id = undef; # replace NULL with a proper value
#my $ezdoctemplatedocument_edit_object_v1_ezdoctemplatedocument_edit_object_v1_request = undef; # replace NULL with a proper value
#my $ezdoctemplatedocument_edit_object_v1_result = $api->ezdoctemplatedocument_edit_object_v1(pki_ezdoctemplatedocument_id => $ezdoctemplatedocument_edit_object_v1_pki_ezdoctemplatedocument_id, ezdoctemplatedocument_edit_object_v1_request => $ezdoctemplatedocument_edit_object_v1_ezdoctemplatedocument_edit_object_v1_request);

#
# ezdoctemplatedocument_get_autocomplete_v2 test
#
# uncomment below and update the test
#my $ezdoctemplatedocument_get_autocomplete_v2_s_selector = undef; # replace NULL with a proper value
#my $ezdoctemplatedocument_get_autocomplete_v2_e_type = undef; # replace NULL with a proper value
#my $ezdoctemplatedocument_get_autocomplete_v2_fki_ezsignfoldertype_id = undef; # replace NULL with a proper value
#my $ezdoctemplatedocument_get_autocomplete_v2_e_filter_active = undef; # replace NULL with a proper value
#my $ezdoctemplatedocument_get_autocomplete_v2_s_query = undef; # replace NULL with a proper value
#my $ezdoctemplatedocument_get_autocomplete_v2_accept_language = undef; # replace NULL with a proper value
#my $ezdoctemplatedocument_get_autocomplete_v2_result = $api->ezdoctemplatedocument_get_autocomplete_v2(s_selector => $ezdoctemplatedocument_get_autocomplete_v2_s_selector, e_type => $ezdoctemplatedocument_get_autocomplete_v2_e_type, fki_ezsignfoldertype_id => $ezdoctemplatedocument_get_autocomplete_v2_fki_ezsignfoldertype_id, e_filter_active => $ezdoctemplatedocument_get_autocomplete_v2_e_filter_active, s_query => $ezdoctemplatedocument_get_autocomplete_v2_s_query, accept_language => $ezdoctemplatedocument_get_autocomplete_v2_accept_language);

#
# ezdoctemplatedocument_get_list_v1 test
#
# uncomment below and update the test
#my $ezdoctemplatedocument_get_list_v1_e_order_by = undef; # replace NULL with a proper value
#my $ezdoctemplatedocument_get_list_v1_i_row_max = undef; # replace NULL with a proper value
#my $ezdoctemplatedocument_get_list_v1_i_row_offset = undef; # replace NULL with a proper value
#my $ezdoctemplatedocument_get_list_v1_accept_language = undef; # replace NULL with a proper value
#my $ezdoctemplatedocument_get_list_v1_s_filter = undef; # replace NULL with a proper value
#my $ezdoctemplatedocument_get_list_v1_result = $api->ezdoctemplatedocument_get_list_v1(e_order_by => $ezdoctemplatedocument_get_list_v1_e_order_by, i_row_max => $ezdoctemplatedocument_get_list_v1_i_row_max, i_row_offset => $ezdoctemplatedocument_get_list_v1_i_row_offset, accept_language => $ezdoctemplatedocument_get_list_v1_accept_language, s_filter => $ezdoctemplatedocument_get_list_v1_s_filter);

#
# ezdoctemplatedocument_get_object_v2 test
#
# uncomment below and update the test
#my $ezdoctemplatedocument_get_object_v2_pki_ezdoctemplatedocument_id = undef; # replace NULL with a proper value
#my $ezdoctemplatedocument_get_object_v2_result = $api->ezdoctemplatedocument_get_object_v2(pki_ezdoctemplatedocument_id => $ezdoctemplatedocument_get_object_v2_pki_ezdoctemplatedocument_id);

#
# ezdoctemplatedocument_patch_object_v1 test
#
# uncomment below and update the test
#my $ezdoctemplatedocument_patch_object_v1_pki_ezdoctemplatedocument_id = undef; # replace NULL with a proper value
#my $ezdoctemplatedocument_patch_object_v1_ezdoctemplatedocument_patch_object_v1_request = undef; # replace NULL with a proper value
#my $ezdoctemplatedocument_patch_object_v1_result = $api->ezdoctemplatedocument_patch_object_v1(pki_ezdoctemplatedocument_id => $ezdoctemplatedocument_patch_object_v1_pki_ezdoctemplatedocument_id, ezdoctemplatedocument_patch_object_v1_request => $ezdoctemplatedocument_patch_object_v1_ezdoctemplatedocument_patch_object_v1_request);


done_testing();
