=begin comment

eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.1.9
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('EzmaxApi::ObjectEzsignbulksendsignermappingApi');

my $api = EzmaxApi::ObjectEzsignbulksendsignermappingApi->new();
isa_ok($api, 'EzmaxApi::ObjectEzsignbulksendsignermappingApi');

#
# ezsignbulksendsignermapping_create_object_v1 test
#
# uncomment below and update the test
#my $ezsignbulksendsignermapping_create_object_v1_ezsignbulksendsignermapping_create_object_v1_request = undef; # replace NULL with a proper value
#my $ezsignbulksendsignermapping_create_object_v1_result = $api->ezsignbulksendsignermapping_create_object_v1(ezsignbulksendsignermapping_create_object_v1_request => $ezsignbulksendsignermapping_create_object_v1_ezsignbulksendsignermapping_create_object_v1_request);

#
# ezsignbulksendsignermapping_delete_object_v1 test
#
# uncomment below and update the test
#my $ezsignbulksendsignermapping_delete_object_v1_pki_ezsignbulksendsignermapping_id = undef; # replace NULL with a proper value
#my $ezsignbulksendsignermapping_delete_object_v1_result = $api->ezsignbulksendsignermapping_delete_object_v1(pki_ezsignbulksendsignermapping_id => $ezsignbulksendsignermapping_delete_object_v1_pki_ezsignbulksendsignermapping_id);

#
# ezsignbulksendsignermapping_get_object_v1 test
#
# uncomment below and update the test
#my $ezsignbulksendsignermapping_get_object_v1_pki_ezsignbulksendsignermapping_id = undef; # replace NULL with a proper value
#my $ezsignbulksendsignermapping_get_object_v1_result = $api->ezsignbulksendsignermapping_get_object_v1(pki_ezsignbulksendsignermapping_id => $ezsignbulksendsignermapping_get_object_v1_pki_ezsignbulksendsignermapping_id);

