=begin comment

eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.1.18
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('EzmaxApi::ObjectSubnetApi');

my $api = EzmaxApi::ObjectSubnetApi->new();
isa_ok($api, 'EzmaxApi::ObjectSubnetApi');

#
# subnet_create_object_v1 test
#
# uncomment below and update the test
#my $subnet_create_object_v1_subnet_create_object_v1_request = undef; # replace NULL with a proper value
#my $subnet_create_object_v1_result = $api->subnet_create_object_v1(subnet_create_object_v1_request => $subnet_create_object_v1_subnet_create_object_v1_request);

#
# subnet_delete_object_v1 test
#
# uncomment below and update the test
#my $subnet_delete_object_v1_pki_subnet_id = undef; # replace NULL with a proper value
#my $subnet_delete_object_v1_result = $api->subnet_delete_object_v1(pki_subnet_id => $subnet_delete_object_v1_pki_subnet_id);

#
# subnet_edit_object_v1 test
#
# uncomment below and update the test
#my $subnet_edit_object_v1_pki_subnet_id = undef; # replace NULL with a proper value
#my $subnet_edit_object_v1_subnet_edit_object_v1_request = undef; # replace NULL with a proper value
#my $subnet_edit_object_v1_result = $api->subnet_edit_object_v1(pki_subnet_id => $subnet_edit_object_v1_pki_subnet_id, subnet_edit_object_v1_request => $subnet_edit_object_v1_subnet_edit_object_v1_request);

#
# subnet_get_object_v2 test
#
# uncomment below and update the test
#my $subnet_get_object_v2_pki_subnet_id = undef; # replace NULL with a proper value
#my $subnet_get_object_v2_result = $api->subnet_get_object_v2(pki_subnet_id => $subnet_get_object_v2_pki_subnet_id);

