=begin comment

eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.1.17
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('EzmaxApi::ObjectEzsigntemplatepackagemembershipApi');

my $api = EzmaxApi::ObjectEzsigntemplatepackagemembershipApi->new();
isa_ok($api, 'EzmaxApi::ObjectEzsigntemplatepackagemembershipApi');

#
# ezsigntemplatepackagemembership_create_object_v1 test
#
# uncomment below and update the test
#my $ezsigntemplatepackagemembership_create_object_v1_ezsigntemplatepackagemembership_create_object_v1_request = undef; # replace NULL with a proper value
#my $ezsigntemplatepackagemembership_create_object_v1_result = $api->ezsigntemplatepackagemembership_create_object_v1(ezsigntemplatepackagemembership_create_object_v1_request => $ezsigntemplatepackagemembership_create_object_v1_ezsigntemplatepackagemembership_create_object_v1_request);

#
# ezsigntemplatepackagemembership_delete_object_v1 test
#
# uncomment below and update the test
#my $ezsigntemplatepackagemembership_delete_object_v1_pki_ezsigntemplatepackagemembership_id = undef; # replace NULL with a proper value
#my $ezsigntemplatepackagemembership_delete_object_v1_result = $api->ezsigntemplatepackagemembership_delete_object_v1(pki_ezsigntemplatepackagemembership_id => $ezsigntemplatepackagemembership_delete_object_v1_pki_ezsigntemplatepackagemembership_id);

#
# ezsigntemplatepackagemembership_get_object_v1 test
#
# uncomment below and update the test
#my $ezsigntemplatepackagemembership_get_object_v1_pki_ezsigntemplatepackagemembership_id = undef; # replace NULL with a proper value
#my $ezsigntemplatepackagemembership_get_object_v1_result = $api->ezsigntemplatepackagemembership_get_object_v1(pki_ezsigntemplatepackagemembership_id => $ezsigntemplatepackagemembership_get_object_v1_pki_ezsigntemplatepackagemembership_id);

#
# ezsigntemplatepackagemembership_get_object_v2 test
#
# uncomment below and update the test
#my $ezsigntemplatepackagemembership_get_object_v2_pki_ezsigntemplatepackagemembership_id = undef; # replace NULL with a proper value
#my $ezsigntemplatepackagemembership_get_object_v2_result = $api->ezsigntemplatepackagemembership_get_object_v2(pki_ezsigntemplatepackagemembership_id => $ezsigntemplatepackagemembership_get_object_v2_pki_ezsigntemplatepackagemembership_id);

