=begin comment

eZmax API Definition

This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.0.31
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('EzmaxApi::ObjectEzsignfolderApi');

my $api = EzmaxApi::ObjectEzsignfolderApi->new();
isa_ok($api, 'EzmaxApi::ObjectEzsignfolderApi');

#
# ezsignfolder_create_object_v1 test
#
{
    my $ezsignfolder_create_object_v1_request = undef; # replace NULL with a proper value
    my $result = $api->ezsignfolder_create_object_v1(ezsignfolder_create_object_v1_request => $ezsignfolder_create_object_v1_request);
}

#
# ezsignfolder_delete_object_v1 test
#
{
    my $pki_ezsignfolder_id = undef; # replace NULL with a proper value
    my $result = $api->ezsignfolder_delete_object_v1(pki_ezsignfolder_id => $pki_ezsignfolder_id);
}

#
# ezsignfolder_get_children_v1 test
#
{
    my $pki_ezsignfolder_id = undef; # replace NULL with a proper value
    my $result = $api->ezsignfolder_get_children_v1(pki_ezsignfolder_id => $pki_ezsignfolder_id);
}

#
# ezsignfolder_get_object_v1 test
#
{
    my $pki_ezsignfolder_id = undef; # replace NULL with a proper value
    my $result = $api->ezsignfolder_get_object_v1(pki_ezsignfolder_id => $pki_ezsignfolder_id);
}

#
# ezsignfolder_send_v1 test
#
{
    my $pki_ezsignfolder_id = undef; # replace NULL with a proper value
    my $ezsignfolder_send_v1_request = undef; # replace NULL with a proper value
    my $result = $api->ezsignfolder_send_v1(pki_ezsignfolder_id => $pki_ezsignfolder_id, ezsignfolder_send_v1_request => $ezsignfolder_send_v1_request);
}


1;
