=begin comment

eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.2.0
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('EzmaxApi::ObjectVariableexpenseApi');

my $api = EzmaxApi::ObjectVariableexpenseApi->new();
isa_ok($api, 'EzmaxApi::ObjectVariableexpenseApi');

#
# variableexpense_create_object_v1 test
#
# uncomment below and update the test
#my $variableexpense_create_object_v1_variableexpense_create_object_v1_request = undef; # replace NULL with a proper value
#my $variableexpense_create_object_v1_result = $api->variableexpense_create_object_v1(variableexpense_create_object_v1_request => $variableexpense_create_object_v1_variableexpense_create_object_v1_request);

#
# variableexpense_edit_object_v1 test
#
# uncomment below and update the test
#my $variableexpense_edit_object_v1_pki_variableexpense_id = undef; # replace NULL with a proper value
#my $variableexpense_edit_object_v1_variableexpense_edit_object_v1_request = undef; # replace NULL with a proper value
#my $variableexpense_edit_object_v1_result = $api->variableexpense_edit_object_v1(pki_variableexpense_id => $variableexpense_edit_object_v1_pki_variableexpense_id, variableexpense_edit_object_v1_request => $variableexpense_edit_object_v1_variableexpense_edit_object_v1_request);

#
# variableexpense_get_autocomplete_v2 test
#
# uncomment below and update the test
#my $variableexpense_get_autocomplete_v2_s_selector = undef; # replace NULL with a proper value
#my $variableexpense_get_autocomplete_v2_e_filter_active = undef; # replace NULL with a proper value
#my $variableexpense_get_autocomplete_v2_s_query = undef; # replace NULL with a proper value
#my $variableexpense_get_autocomplete_v2_accept_language = undef; # replace NULL with a proper value
#my $variableexpense_get_autocomplete_v2_result = $api->variableexpense_get_autocomplete_v2(s_selector => $variableexpense_get_autocomplete_v2_s_selector, e_filter_active => $variableexpense_get_autocomplete_v2_e_filter_active, s_query => $variableexpense_get_autocomplete_v2_s_query, accept_language => $variableexpense_get_autocomplete_v2_accept_language);

#
# variableexpense_get_list_v1 test
#
# uncomment below and update the test
#my $variableexpense_get_list_v1_e_order_by = undef; # replace NULL with a proper value
#my $variableexpense_get_list_v1_i_row_max = undef; # replace NULL with a proper value
#my $variableexpense_get_list_v1_i_row_offset = undef; # replace NULL with a proper value
#my $variableexpense_get_list_v1_accept_language = undef; # replace NULL with a proper value
#my $variableexpense_get_list_v1_s_filter = undef; # replace NULL with a proper value
#my $variableexpense_get_list_v1_result = $api->variableexpense_get_list_v1(e_order_by => $variableexpense_get_list_v1_e_order_by, i_row_max => $variableexpense_get_list_v1_i_row_max, i_row_offset => $variableexpense_get_list_v1_i_row_offset, accept_language => $variableexpense_get_list_v1_accept_language, s_filter => $variableexpense_get_list_v1_s_filter);

#
# variableexpense_get_object_v2 test
#
# uncomment below and update the test
#my $variableexpense_get_object_v2_pki_variableexpense_id = undef; # replace NULL with a proper value
#my $variableexpense_get_object_v2_result = $api->variableexpense_get_object_v2(pki_variableexpense_id => $variableexpense_get_object_v2_pki_variableexpense_id);


done_testing();
