=begin comment

eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.2.0
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('EzmaxApi::ObjectModulegroupApi');

my $api = EzmaxApi::ObjectModulegroupApi->new();
isa_ok($api, 'EzmaxApi::ObjectModulegroupApi');

#
# modulegroup_get_all_v1 test
#
# uncomment below and update the test
#my $modulegroup_get_all_v1_e_context = undef; # replace NULL with a proper value
#my $modulegroup_get_all_v1_result = $api->modulegroup_get_all_v1(e_context => $modulegroup_get_all_v1_e_context);


done_testing();
