=begin comment

eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.2.1
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('EzmaxApi::ObjectInvoiceApi');

my $api = EzmaxApi::ObjectInvoiceApi->new();
isa_ok($api, 'EzmaxApi::ObjectInvoiceApi');

#
# invoice_get_attachments_v1 test
#
# uncomment below and update the test
#my $invoice_get_attachments_v1_pki_invoice_id = undef; # replace NULL with a proper value
#my $invoice_get_attachments_v1_result = $api->invoice_get_attachments_v1(pki_invoice_id => $invoice_get_attachments_v1_pki_invoice_id);

#
# invoice_get_communication_count_v1 test
#
# uncomment below and update the test
#my $invoice_get_communication_count_v1_pki_invoice_id = undef; # replace NULL with a proper value
#my $invoice_get_communication_count_v1_result = $api->invoice_get_communication_count_v1(pki_invoice_id => $invoice_get_communication_count_v1_pki_invoice_id);

#
# invoice_get_communication_list_v1 test
#
# uncomment below and update the test
#my $invoice_get_communication_list_v1_pki_invoice_id = undef; # replace NULL with a proper value
#my $invoice_get_communication_list_v1_result = $api->invoice_get_communication_list_v1(pki_invoice_id => $invoice_get_communication_list_v1_pki_invoice_id);

#
# invoice_get_communicationrecipients_v1 test
#
# uncomment below and update the test
#my $invoice_get_communicationrecipients_v1_pki_invoice_id = undef; # replace NULL with a proper value
#my $invoice_get_communicationrecipients_v1_result = $api->invoice_get_communicationrecipients_v1(pki_invoice_id => $invoice_get_communicationrecipients_v1_pki_invoice_id);

#
# invoice_get_communicationsenders_v1 test
#
# uncomment below and update the test
#my $invoice_get_communicationsenders_v1_pki_invoice_id = undef; # replace NULL with a proper value
#my $invoice_get_communicationsenders_v1_result = $api->invoice_get_communicationsenders_v1(pki_invoice_id => $invoice_get_communicationsenders_v1_pki_invoice_id);


done_testing();
