=begin comment

eZmax API Definition

This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.0.39
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('EzmaxApi::ObjectEzsignfoldersignerassociationApi');

my $api = EzmaxApi::ObjectEzsignfoldersignerassociationApi->new();
isa_ok($api, 'EzmaxApi::ObjectEzsignfoldersignerassociationApi');

#
# ezsignfoldersignerassociation_create_object_v1 test
#
# uncomment below and update the test
#my $ezsignfoldersignerassociation_create_object_v1_ezsignfoldersignerassociation_create_object_v1_request = undef; # replace NULL with a proper value
#my $ezsignfoldersignerassociation_create_object_v1_result = $api->ezsignfoldersignerassociation_create_object_v1(ezsignfoldersignerassociation_create_object_v1_request => $ezsignfoldersignerassociation_create_object_v1_ezsignfoldersignerassociation_create_object_v1_request);

#
# ezsignfoldersignerassociation_delete_object_v1 test
#
# uncomment below and update the test
#my $ezsignfoldersignerassociation_delete_object_v1_pki_ezsignfoldersignerassociation_id = undef; # replace NULL with a proper value
#my $ezsignfoldersignerassociation_delete_object_v1_result = $api->ezsignfoldersignerassociation_delete_object_v1(pki_ezsignfoldersignerassociation_id => $ezsignfoldersignerassociation_delete_object_v1_pki_ezsignfoldersignerassociation_id);

#
# ezsignfoldersignerassociation_get_children_v1 test
#
# uncomment below and update the test
#my $ezsignfoldersignerassociation_get_children_v1_pki_ezsignfoldersignerassociation_id = undef; # replace NULL with a proper value
#my $ezsignfoldersignerassociation_get_children_v1_result = $api->ezsignfoldersignerassociation_get_children_v1(pki_ezsignfoldersignerassociation_id => $ezsignfoldersignerassociation_get_children_v1_pki_ezsignfoldersignerassociation_id);

#
# ezsignfoldersignerassociation_get_in_person_login_url_v1 test
#
# uncomment below and update the test
#my $ezsignfoldersignerassociation_get_in_person_login_url_v1_pki_ezsignfoldersignerassociation_id = undef; # replace NULL with a proper value
#my $ezsignfoldersignerassociation_get_in_person_login_url_v1_result = $api->ezsignfoldersignerassociation_get_in_person_login_url_v1(pki_ezsignfoldersignerassociation_id => $ezsignfoldersignerassociation_get_in_person_login_url_v1_pki_ezsignfoldersignerassociation_id);

#
# ezsignfoldersignerassociation_get_object_v1 test
#
# uncomment below and update the test
#my $ezsignfoldersignerassociation_get_object_v1_pki_ezsignfoldersignerassociation_id = undef; # replace NULL with a proper value
#my $ezsignfoldersignerassociation_get_object_v1_result = $api->ezsignfoldersignerassociation_get_object_v1(pki_ezsignfoldersignerassociation_id => $ezsignfoldersignerassociation_get_object_v1_pki_ezsignfoldersignerassociation_id);

