=begin comment

eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.1.9
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('EzmaxApi::ObjectEzsignfoldertypeApi');

my $api = EzmaxApi::ObjectEzsignfoldertypeApi->new();
isa_ok($api, 'EzmaxApi::ObjectEzsignfoldertypeApi');

#
# ezsignfoldertype_get_autocomplete_v1 test
#
# uncomment below and update the test
#my $ezsignfoldertype_get_autocomplete_v1_s_selector = undef; # replace NULL with a proper value
#my $ezsignfoldertype_get_autocomplete_v1_s_query = undef; # replace NULL with a proper value
#my $ezsignfoldertype_get_autocomplete_v1_accept_language = undef; # replace NULL with a proper value
#my $ezsignfoldertype_get_autocomplete_v1_result = $api->ezsignfoldertype_get_autocomplete_v1(s_selector => $ezsignfoldertype_get_autocomplete_v1_s_selector, s_query => $ezsignfoldertype_get_autocomplete_v1_s_query, accept_language => $ezsignfoldertype_get_autocomplete_v1_accept_language);

#
# ezsignfoldertype_get_list_v1 test
#
# uncomment below and update the test
#my $ezsignfoldertype_get_list_v1_e_order_by = undef; # replace NULL with a proper value
#my $ezsignfoldertype_get_list_v1_i_row_max = undef; # replace NULL with a proper value
#my $ezsignfoldertype_get_list_v1_i_row_offset = undef; # replace NULL with a proper value
#my $ezsignfoldertype_get_list_v1_accept_language = undef; # replace NULL with a proper value
#my $ezsignfoldertype_get_list_v1_s_filter = undef; # replace NULL with a proper value
#my $ezsignfoldertype_get_list_v1_result = $api->ezsignfoldertype_get_list_v1(e_order_by => $ezsignfoldertype_get_list_v1_e_order_by, i_row_max => $ezsignfoldertype_get_list_v1_i_row_max, i_row_offset => $ezsignfoldertype_get_list_v1_i_row_offset, accept_language => $ezsignfoldertype_get_list_v1_accept_language, s_filter => $ezsignfoldertype_get_list_v1_s_filter);

