=begin comment

eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.2.0
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('EzmaxApi::ObjectSignatureApi');

my $api = EzmaxApi::ObjectSignatureApi->new();
isa_ok($api, 'EzmaxApi::ObjectSignatureApi');

#
# signature_create_object_v1 test
#
# uncomment below and update the test
#my $signature_create_object_v1_signature_create_object_v1_request = undef; # replace NULL with a proper value
#my $signature_create_object_v1_result = $api->signature_create_object_v1(signature_create_object_v1_request => $signature_create_object_v1_signature_create_object_v1_request);

#
# signature_delete_object_v1 test
#
# uncomment below and update the test
#my $signature_delete_object_v1_pki_signature_id = undef; # replace NULL with a proper value
#my $signature_delete_object_v1_result = $api->signature_delete_object_v1(pki_signature_id => $signature_delete_object_v1_pki_signature_id);

#
# signature_edit_object_v1 test
#
# uncomment below and update the test
#my $signature_edit_object_v1_pki_signature_id = undef; # replace NULL with a proper value
#my $signature_edit_object_v1_signature_edit_object_v1_request = undef; # replace NULL with a proper value
#my $signature_edit_object_v1_result = $api->signature_edit_object_v1(pki_signature_id => $signature_edit_object_v1_pki_signature_id, signature_edit_object_v1_request => $signature_edit_object_v1_signature_edit_object_v1_request);

#
# signature_get_object_v2 test
#
# uncomment below and update the test
#my $signature_get_object_v2_pki_signature_id = undef; # replace NULL with a proper value
#my $signature_get_object_v2_result = $api->signature_get_object_v2(pki_signature_id => $signature_get_object_v2_pki_signature_id);


done_testing();
