=begin comment

eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

The version of the OpenAPI document: 1.1.7
Contact: support-api@ezmax.ca
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('EzmaxApi::ObjectActivesessionApi');

my $api = EzmaxApi::ObjectActivesessionApi->new();
isa_ok($api, 'EzmaxApi::ObjectActivesessionApi');

#
# activesession_get_current_v1 test
#
# uncomment below and update the test
#my $activesession_get_current_v1_result = $api->activesession_get_current_v1();

